stages:
  - deploy
  - build
  - op

deploy-job:
  stage: deploy
  tags:
    - shop
  only:
    - master
  script:
    - npm install
    - npm run build
    - rm -rf /webapps/shop/*
    - mv ./dist/* /webapps/shop/