stages:
  - deploy
  - build
  - op

deploy-job:
  stage: deploy
  tags:
    - shop
  only:
    - master
  script:
    - cd /home/django/builds/6Nxw5Yry/0/leolikang/shopp-manage
    - npm install
    - npm run build
    - rm -rf /webapps/shop/*
    - mv /home/django/builds/6Nxw5Yry/0/leolikang/shopp-manage/dist/* /webapps/shop/